remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Stap binnen in het digitale atelier van ELDENDO.
description: '   De wereld door mijn ogen, gevormd door mijn projecten en gevoed door mijn interesses.'
